print('Em linhas de código, a arte se revela,\nPython se destaca, de forma singela.\nIdentação precisa, seu charme discreto,\nTorna a programação um caminho direto.')
print('')
print('Comloopsque iteram, decisões a tomar,\nCada função em Python, há algo a explorar.\nManipula os dados com pandas, sem parar,\nE na simplicidade do código, vê-se a lógica brilhar.')
print('')
print('Uma lista, um dicionário, tudo bem organizado,\nEm Python, cada estrutura tem seu lugar bem marcado.\nDestrings a números, tudo se conecta,\nA linguagem é poderosa, flexível e direta.')